<?php
$config['evaluate_data'] = array(
	'is_vip' => FALSE,
	'has_score' => TRUE,
	'show_question_in_result' => FALSE,
	'description' => '在根据你自己的实际情况，对每个问题作出回答：是、否或答不上。总分60分，学习习惯水平:0-20您的学习习惯很不好21-40您的学习习惯不太好41-60您的学习习惯比较好61-80您的学习习惯很好',
	'sumup' => '总分60分，学习习惯水平:0-20您的学习习惯很不好21-40您的学习习惯不太好41-60您的学习习惯比较好61-80您的学习习惯很好',
	'questions' => array(
		1 => array(
			'name' => '你的预习是凭兴致或经常忘记吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		2 => array(
			'name' => '你是否要等老师布置预习要求才去预习？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		3 => array(
			'name' => '你是否着重预习薄弱的学科，其它学科则一般预习？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		4 => array(
			'name' => '你能找出预习内容中的重点和关键之处吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		5 => array(
			'name' => '你能努力解决预习中遇到的某些问题吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		6 => array(
			'name' => '你觉得预习是一件困难的事吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		7 => array(
			'name' => '你能记得在预习中遇到的疑点和难点吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		8 => array(
			'name' => '你对预习的内容基本上做到心中有数吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		9 => array(
			'name' => '能说出不同学科预习的经验和体会吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		10 => array(
			'name' => '你能通过预习便学习的效果有提高吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		11 => array(
			'name' => '你能在上课一开始就很快地集中注意力听讲吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		12 => array(
			'name' => '你上课能不讲废话、不开小差、不受别人和外界的影响吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		13 => array(
			'name' => '你经常把讲课内容与预习中的问题或学过的知识联系起来思考吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		14 => array(
			'name' => '你在同学回答问题时能在脑子里积极思考问题答案吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		15 => array(
			'name' => '你能主动举手回答老师的提问和参加讨论吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		16 => array(
			'name' => '你对不明白的地方，能在上课提出来或下课问老师吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		17 => array(
			'name' => '你能根据讲课的要点主动记笔记而不仅仅照黑板上的记吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		18 => array(
			'name' => '你在课后能看清和看懂自己的笔记吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		19 => array(
			'name' => '上完课你能用自己的话概括一堂课所学的主要内容吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		20 => array(
			'name' => '你对老师的讲课经常有评价和看法吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		21 => array(
			'name' => '你在课后能先复习课上学的内容，然后再做作业吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		22 => array(
			'name' => '你复习时只是把课文重看一遍吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		23 => array(
			'name' => '你能及时整理笔记并把笔记和书本内容结合起来思考吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		24 => array(
			'name' => '经过复习后，你对所学的内容是否弄清了疑问或加深了理解？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		25 => array(
			'name' => '做完作业你对前些日子学的内容能否重新温习？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		26 => array(
			'name' => '一单元学完后，你能否自学地进行一次系统复习和小结？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		27 => array(
			'name' => '你是仅仅为了测验才复习的吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		28 => array(
			'name' => '阶段复习时你能否针对自己的薄弱环节来加深理解和练习？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		29 => array(
			'name' => '系统复习时，你能否把前后知识联系起来从整体上去理解和融合贯通？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		30 => array(
			'name' => '你能运用多种记忆的方法提高复习效果吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		31 => array(
			'name' => '你有抄袭同学作业的习惯吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		32 => array(
			'name' => '你做作业要父母督促吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		33 => array(
			'name' => '作业本发下来你能认真找出错误的原因，并自觉订正吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		34 => array(
			'name' => '你的作业整洁，并符合规范格式吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		35 => array(
			'name' => '你做作业时，一有困难就马上问别人吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		36 => array(
			'name' => '别人帮助你时，你希望别人给思路，而不愿意完全帮你解答吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		37 => array(
			'name' => '你总是匆匆忙忙做完作业而不检查吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		38 => array(
			'name' => '你做作业时常常开小差或常常停下做别的事吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		39 => array(
			'name' => '你对做作业时间有规定，而不拖延完成吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
		40 => array(
			'name' => '你能做到书写作业和口头作业都能按要求完成吗？（）',
			'type' => 'radio',
			'options' => array(
				1 => array('text' => '是',
							'score' => 2,
						),
				2 => array('text' => '否',
							'score' => 0,
						),
				3 => array('text' => '答不上',
							'score' => 1,
						),
			),
		),
	),
);


?>